name: Initializr

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server -XX:+UseG1GC"
  TERM: xterm-256color
  JDK_CURRENT: 11.0.8

##########################################################################

on:
  push:
    branches: [ heroku-casinit  ]
  pull_request:
    branches: [ heroku-casinit  ]

##########################################################################

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_CURRENT }}
      - name: Build Overlay
        run: |
          ./gradlew --build-cache --configure-on-demand --no-daemon clean build -x test -x javadoc -x check --parallel
          java -jar app/build/libs/app.jar &
          sleep 10
          mkdir tmp
          cd tmp
          curl http://localhost:8080/starter.tgz -d dependencies=core | tar -xzvf -
          ./gradlew clean build --refresh-dependencies
